var total = 0;
var productArray = new Array();
var costArray = new Array();
var quantityArray = new Array();
var scriptKey = new Array();
var scriptValue = new Array();

productArray.push("1-TEAHOUSE AFTERNOON");
productArray.push("2-TEAHOUSE ALLROUNDER");
productArray.push("3-TEAHOUSE BREAKFAST");
productArray.push("4-GOODNIGHT GREEN ");
productArray.push("5-SMOKEY GREY");
productArray.push("6-JASMINE BUDDA PEARLS");
productArray.push("7-WHITE PEONY");
productArray.push("8-CHINA CITRUS");
productArray.push("9-EMPRESS GARDEN");
productArray.push("10-POPCORN GREEN TEA");
productArray.push("11-GREEN TEA WITH JASMINE");
productArray.push("12-GUNPOWDER");
productArray.push("13-JAPANESE LIME GREEN TEA");
productArray.push("14-MOROCCAN MINT ");
productArray.push("15-ORGANIC JAPANESE BANCHA");
productArray.push("16-AFTER DINNER");
productArray.push("17-GOLDEN DAN CHONG");
productArray.push("18-WHITE DRAGON");
productArray.push("19-ARCTIC FIRE");
productArray.push("20-AUSTRALIAN DAINTREE");
productArray.push("21-BLACK VANILLA");
productArray.push("22-CEYLON ORANGE PEKOE");
productArray.push("23-CHOCOLATE CHAI");
productArray.push("24-CINNAMON APPLE");
productArray.push("25-CINNAMON CITRUS");
productArray.push("26-EARL GREY");
productArray.push("27-FARMHOUSE BLEND");
productArray.push("28-FRENCH EARL GREY ");
productArray.push("29-GOLDEN BLACK YUNNAN");
productArray.push("30-GOLDEN DARJEELING FTGOP1");
productArray.push("31-INDIA ASSAM (DIKOM)");
productArray.push("32-IRISH BREAKFAST");
productArray.push("33-JELLYBEAN");
productArray.push("34-KEEMUN");
productArray.push("35-MAH JONGG");
productArray.push("36-MARCO ORIENTAL");
productArray.push("37-MARSALA CHAI");
productArray.push("38-MORNING DELIGHT");
productArray.push("39-ORGANIC ENGLISH BREAKFAST");
productArray.push("40-ORGANIC INDIA ASSAM");
productArray.push("41-RASPBERRY BLACK ");
productArray.push("42-ROSE GREY");
productArray.push("43-RUSSIAN CARAVAN ");
productArray.push("44-SCOTTISH BREAKFAST");
productArray.push("45-SPICY CHAI");
productArray.push("46-ST. PETERSBURG SILVERTIP");
productArray.push("47-TARRY LAPSANG SOUCHONG");
productArray.push("48-TURKISH BLACK");
productArray.push("49-PURE CHAMOMILE");
productArray.push("50-CHAMOMILE APPLE");
productArray.push("51-PURE PEPPERMINT");
productArray.push("52-LEMONGRASS");
productArray.push("53-ORGANIC ROOIBOS");
productArray.push("54-HONEYSWEET");
productArray.push("55-SPICE MAGIC");
productArray.push("56-LEMONGINGER");
productArray.push("57-BERRY FAIRY");
productArray.push("58-CLASSIC TURKISH APPL");
productArray.push("59-apple muffin");
productArray.push("60-nuts muffin");
productArray.push("61-Teahouse Teapots");
productArray.push("62-A perfect cup of tea scoop");
productArray.push("63-Mesh Nippers Infuser");




costArray.push("1");
costArray.push("2");
costArray.push("3");
costArray.push("4");
costArray.push("5");
costArray.push("6");
costArray.push("7");
costArray.push("8");
costArray.push("9");
costArray.push("10");
costArray.push("11");
costArray.push("12");
costArray.push("13");
costArray.push("14");
costArray.push("15");
costArray.push("16");
costArray.push("17");
costArray.push("18");
costArray.push("19");
costArray.push("20");
costArray.push("21");
costArray.push("22");
costArray.push("23");
costArray.push("24");
costArray.push("25");
costArray.push("26");
costArray.push("27");
costArray.push("28");
costArray.push("29");
costArray.push("30");
costArray.push("31");
costArray.push("32");
costArray.push("33");
costArray.push("34");
costArray.push("35");
costArray.push("36");
costArray.push("37");
costArray.push("38");
costArray.push("39");
costArray.push("40");
costArray.push("41");
costArray.push("42");
costArray.push("43");
costArray.push("44");
costArray.push("45");
costArray.push("46");
costArray.push("47");
costArray.push("48");
costArray.push("49");
costArray.push("50");
costArray.push("51");
costArray.push("52");
costArray.push("53");
costArray.push("54");
costArray.push("55");
costArray.push("56");
costArray.push("57");
costArray.push("58");
costArray.push("59");
costArray.push("60");
costArray.push("61")
costArray.push("62")
costArray.push("63")

for(var k = 0; k < productArray.length; k++)
{
	quantityArray[k] = 0;
}